Watchlist/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Watchlist.Data;
using Microsoft.AspNetCore.Authorization;
using Watchlist.Models;
using Microsoft.AspNetCore.Identity;
using Watchlist.Services;
using Watchlist.Repositories;

namespace Watchlist.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieRepository _movieRepository;
        private readonly IUserMovieRepository _userMovieRepository;
        private readonly IUserService _userService;

        public MoviesController(
            IMovieRepository movieRepository,
            IUserMovieRepository userMovieRepository,
            IUserService userService
        )
        {
            _movieRepository = movieRepository;
            _userService = userService;
            _userMovieRepository = userMovieRepository;
             
        }


        // GET: Movies
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _movieRepository.GetMoviesAsync(HttpContext));
        }


        [Authorize]
        [HttpGet]
        public async Task<JsonResult> AddRemove(int id,int val)
        {
            int retval = -1;
            var userId = await _userService.GetCurrentUserIdAsync(HttpContext);
            if (val == 1)
            {
                // if a record exists in UserMovies that contains both the user’s
                // and movie’s Ids, then the movie is in the watchlist and can
                // be removed
                var movie = await _userMovieRepository.GetUserMovieAsync(userId, id);
                if (movie != null)
                {
                    await _userMovieRepository.DeleteAsync(movie);
                    retval = 0;
                }

            }
            else
            {
                // the movie is not currently in the watchlist, so we need to
                // build a new UserMovie object and add it to the database
                await _userMovieRepository.CreateAsync(
                    new UserMovie
                    {
                        UserId = userId,
                        MovieId = id,
                        Watched = false,
                        Rating = 0
                    }
                );
                retval = 1;
            }

            // and our return value (-1, 0, or 1) back to the script that called
            // this method from the Index page
            return Json(retval);
        }

        // GET: Movies/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _movieRepository.GetMoviesAsync(id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Year")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                await _movieRepository.CreateAsync(movie);
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _movieRepository.GetMoviesAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Year")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _movieRepository.UpdateAsync(movie);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_movieRepository.MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _movieRepository.GetMoviesAsync(id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _movieRepository.GetMoviesAsync(id);
            await _movieRepository.CreateAsync(movie);
            return RedirectToAction(nameof(Index));
        }

    }
}

Watchlist/Controllers/WatchlistController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Watchlist.Data;
using Watchlist.Models;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Watchlist.Services;
using Watchlist.Repositories;

namespace Watchlist.Controllers
{
    [Authorize]
    public class WatchlistController : Controller
    {
        private readonly IUserMovieRepository _userMovieRepository;
        private readonly IUserService _userService;

        public WatchlistController(
            IUserMovieRepository userMovieRepository,
            IUserService userService
        )
        {
            _userMovieRepository = userMovieRepository;
            _userService = userService;
        }


        public async Task<IActionResult> Index()
        {
            var id = await _userService.GetCurrentUserIdAsync(HttpContext);

            //var userMovies = _context.UserMovies.Select(x => new MovieViewModel
            //{
            //    UserId = x.UserId,
            //    MovieId = x.MovieId,
            //    Title = x.Movie.Title,
            //    Year = x.Movie.Year,
            //    Watched = x.Watched,
            //    InWatchlist = true,
            //    Rating = x.Rating
            //});

            //var model = userMovies.Where(u => u.UserId == id).ToList();

            return View(await _userMovieRepository.GetUserMovieAsync(id));
        }
    }
}

Watchlist/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Watchlist.Data
@inject SignInManager<ApplicationUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Watchlist</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Watchlist</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Watchlist" asp-action="Index">Watchlist</a>
                            </li>
                        }                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Watchlist - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>